# Generated by Django 3.0.3 on 2020-03-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=512)),
            ],
            options={
                'db_table': 'commodities_commodity',
            },
        ),
        migrations.CreateModel(
            name='TradePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=512)),
            ],
            options={
                'db_table': 'commodities_trade_partner',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Shipping'), (2, 'Receiving')])),
                ('quantity', models.PositiveIntegerField()),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodity')),
                ('trade_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodities.TradePartner')),
            ],
            options={
                'db_table': 'commodities_inventory',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='trade_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodities.TradePartner'),
        ),
    ]
