# Generated by Django 3.0.3 on 2020-04-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodities', '0002_auto_20200330_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('a', 'Add'), ('m', 'Modify'), ('d', 'Delete')], max_length=2)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('type', models.IntegerField(choices=[(1, 'Shipping'), (2, 'Receiving')])),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodities.Inventory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commodities_inventory_history',
                'ordering': ['id'],
            },
        ),
    ]
