# Generated by Django 3.0.3 on 2020-04-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_inventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='inventory',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodities.Inventory'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['created_at'], name='commodities_created_ca1fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['inventory', 'created_at'], name='commodities_invento_c22deb_idx'),
        ),
    ]
